version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /assembly-to-fake-reads.wdl
    name: assembly-to-fake-reads
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
