version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /assembly-to-fake-reads.wdl
    name: assembly-to-fake-reads
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
  - subclass: WDL
    primaryDescriptorPath: /downsample-fastq.wdl
    name: downsample-fastqs
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
  - subclass: WDL
    primaryDescriptorPath: /generate-vcf.wdl
    name: generate-vcf
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu
  - subclass: WDL
    primaryDescriptorPath: /generate-vcf-alt.wdl
    name: generate-vcf-with-kent
    authors:
      - name: Nathaniel L. Matteson
        email: nmatteson@bwh.harvard.edu